export default [
  { path: '/', redirect: '/admin/workbench/statistics' },
  { path: '/admin', redirect: '/admin/workbench/statistics' },
  { path: '/admin/statistics', redirect: '/admin/workbench/statistics', hidden: true },
  { path: '/admin/user', redirect: '/admin/relation/user', hidden: true },
  { path: '/admin/friend_apply', redirect: '/admin/relation/friend-apply', hidden: true },
  { path: '/admin/chat_room', redirect: '/admin/chat/rooms', hidden: true },
  { path: '/admin/group', redirect: '/admin/chat/groups', hidden: true },
  { path: '/admin/notification', redirect: '/admin/ops/notifications', hidden: true },
  { path: '/admin/ai_chat', redirect: '/admin/ops/ai-chat', hidden: true },
  { path: '/admin/loglist', redirect: '/admin/ops/logs', hidden: true },
  { path: '/admin/log', redirect: '/admin/ops/log', hidden: true },
  { path: '/admin/log/file/upload', redirect: '/admin/ops/log/file-upload', hidden: true },
  { path: '/admin/log/api', redirect: '/admin/ops/log/api-access', hidden: true },
  { path: '/admin/log/operation', redirect: '/admin/ops/log/operation', hidden: true },
  { path: '/admin/log/login', redirect: '/admin/ops/log/login', hidden: true },
  {
    name: '工作台',
    path: '/admin/workbench',
    icon: 'DashboardOutlined',
    access: 'canAdmin',
    routes: [
      { path: '/admin/workbench', redirect: '/admin/workbench/statistics' },
      {
        name: '数据概览',
        path: '/admin/workbench/statistics',
        component: './Admin/Statistics',
        icon: 'BarChartOutlined',
      },
    ],
  },
  {
    name: '用户与关系',
    path: '/admin/relation',
    icon: 'UsergroupAddOutlined',
    access: 'canAdmin',
    routes: [
      { path: '/admin/relation', redirect: '/admin/relation/user' },
      {
        name: '用户管理',
        path: '/admin/relation/user',
        component: './Admin/UserList',
        icon: 'UserOutlined',
      },
      {
        name: '好友申请',
        path: '/admin/relation/friend-apply',
        component: './Admin/FriendApplyList',
        icon: 'UserAddOutlined',
      },
    ],
  },
  {
    name: '聊天治理',
    path: '/admin/chat',
    icon: 'MessageOutlined',
    access: 'canAdmin',
    routes: [
      { path: '/admin/chat', redirect: '/admin/chat/rooms' },
      {
        name: '聊天室管理',
        path: '/admin/chat/rooms',
        component: './Admin/ChatRoomList',
        icon: 'GroupOutlined',
      },
      {
        name: '群组管理',
        path: '/admin/chat/groups',
        component: './Admin/GroupList',
        icon: 'TeamOutlined',
      },
    ],
  },
  {
    name: '运营审计',
    path: '/admin/ops',
    icon: 'AuditOutlined',
    access: 'canAdmin',
    routes: [
      { path: '/admin/ops', redirect: '/admin/ops/notifications' },
      {
        name: '通知管理',
        path: '/admin/ops/notifications',
        component: './Admin/NotificationList',
        icon: 'NotificationOutlined',
      },
      {
        name: 'AI 对话审计',
        path: '/admin/ops/ai-chat',
        component: './Admin/AIChatRecordList',
        icon: 'RobotOutlined',
      },
      {
        name: '日志总览',
        path: '/admin/ops/logs',
        component: './Admin/LogList',
        icon: 'FileTextOutlined',
      },
      {
        name: '日志明细',
        path: '/admin/ops/log',
        icon: 'HistoryOutlined',
        routes: [
          { path: '/admin/ops/log', redirect: '/admin/ops/log/operation' },
          {
            name: '文件上传日志',
            path: '/admin/ops/log/file-upload',
            component: './Admin/Log/FileUploadRecord',
          },
          {
            name: 'API 访问日志',
            path: '/admin/ops/log/api-access',
            component: './Admin/Log/ApiAccessLog',
          },
          {
            name: '操作日志',
            path: '/admin/ops/log/operation',
            component: './Admin/Log/OperationLog',
          },
          {
            name: '登录日志',
            path: '/admin/ops/log/login',
            component: './Admin/Log/UserLoginLog',
          },
        ],
      },
    ],
  },
  {
    path: '/user',
    layout: false,
    routes: [
      {
        name: '登录',
        path: '/user/login',
        component: './User/Login',
      },
    ],
  },
  {
    name: '个人中心',
    path: '/account/center',
    component: './Account/Center',
    icon: 'UserOutlined',
    hidden: true,
    access: 'canUser',
  },
  {
    name: 'exception',
    icon: 'warning',
    path: '/exception',
    layout: false,
    routes: [
      {
        path: '/exception',
        redirect: '/exception/403',
      },
      {
        name: '403',
        icon: 'smile',
        path: '/exception/403',
        component: './Exception/403',
      },
      {
        name: '404',
        icon: 'smile',
        path: '/exception/404',
        component: './Exception/404',
      },
      {
        name: '500',
        icon: 'smile',
        path: '/exception/500',
        component: './Exception/500',
      },
    ],
  },
  { path: '*', layout: false, component: './Exception/404' },
];
